MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - "11"                   # [osx and x86_64]
  - "13.3"                 # [osx and arm64]
MACOSX_SDK_VERSION:        # [osx]
  - "11"                   # [osx and x86_64]
  - "13.3"                 # [osx and arm64]
