c_stdlib_version:          # [osx and arm64]
  - "13.3"                 # [osx and arm64]
MACOSX_SDK_VERSION:        # [osx and arm64]
  - "13.3"                 # [osx and arm64]
channel_sources:
  - "conda-forge/label/nanobind_dev,conda-forge"
