{% set name = "mlx" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # There are no sources on PyPI
  url: https://github.com/ml-explore/mlx/archive/v{{ version }}.tar.gz
  sha256: b2667dc54464a1e1c5111a7014b3a2cb1ff9ec9cd9624c41afa60bb8ca6e25fe
  patches:
    - 0001-Use-CMAKE_SYSTEM_PROCESSOR-instead-of-CMAKE_HOST_SYS.patch

build:
  skip: true  # [win or py<39]
  number: 0

requirements:
  build:
    # need python in the build section to properly build the extensions
    - python
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - nanobind
    - blas       # [not (osx and arm64)]
    - libblas    # [not (osx and arm64)]
    - liblapack  # [not (osx and arm64)]
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  source_files:
    - python/
  imports:
    - mlx
    - mlx.core
  requires:
    - pip
    # test dependencies
    - numpy
  commands:
    - pip check
    # Tests are passing only if you have more than 8GB of RAM.
    - python -m unittest discover python/tests  # [osx and arm64]

about:
  home: https://github.com/ml-explore/mlx
  summary: An array framework for Apple silicon
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    MLX is an array framework for machine learning on Apple silicon, brought to you by Apple machine learning research.
  dev_url: https://ml-explore.github.io/mlx/build/html/index.html
  doc_url: https://github.com/ml-explore/mlx

extra:
  recipe-maintainers:
    - xhochy
    - ngam
