{% set name = "mlx" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # There are no sources on PyPI
  url: https://github.com/ml-explore/mlx/archive/v{{ version }}.tar.gz
  sha256: fc4f77af40d8e35b0b2073906c652a8f2e7dc0a93c7b45a3a193d7e5412a8119
  patches:
    - 0001-Use-CMAKE_SYSTEM_PROCESSOR-instead-of-CMAKE_HOST_SYS.patch

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    # need python in the build section to properly build the extensions
    - python
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}    # [not (osx and arm64)]
    - {{ compiler('cxx') }}  # [not (osx and arm64)]
    - cmake
    - ninja
  host:
    - python
    - pip
    - pybind11
    - blas     # [not (osx and arm64)]
    - libblas  # [not (osx and arm64)]
  run:
    - python
    # it appears we need libcxx because we are not using cf compilers...
    - libcxx  # [osx and arm64]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]


test:
  source_files:
    - python/
  imports:
    - mlx
  requires:
    - pip
    # test dependencies
    - numpy
  commands:
    - pip check
    # Tests are passing only if you have more than 8GB of RAM.
    - python -m unittest discover python/tests  # [osx and arm64]

about:
  home: https://github.com/ml-explore/mlx
  summary: An array framework for Apple silicon
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
