{% set name = "mlx" %}
{% set version = "0.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # There are no sources on PyPI
  url: https://github.com/ml-explore/mlx/archive/v{{ version }}.tar.gz
  sha256: 6a86ccb0cb54e45bcc782ed4ca878935e64f24fbc38497f65e606e43d3280f8c
  patches:
    - 0001-More-stable-invocation-of-stub-generation.patch

build:
  skip: true  # [win or py<39 or (osx and x86_64)]
  number: 1

requirements:
  build:
    # need python in the build section to properly build the extensions
    - python
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - nanobind
    - typing_extensions
    - setuptools
    - blas       # [not (osx and arm64)]
    - libblas    # [not (osx and arm64)]
    - liblapack  # [not (osx and arm64)]
  run:
    - python

test:
  source_files:
    - python/
  imports:
    - mlx
    - mlx.core
  requires:
    - pip
    # test dependencies
    - numpy
  commands:
    - pip check
    # Tests are passing only if you have more than 8GB of RAM.
    - python -m unittest discover python/tests  # [osx and arm64]
    - test -f $SP_DIR/mlx/core/__init__.pyi

about:
  home: https://github.com/ml-explore/mlx
  summary: An array framework for Apple silicon
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    MLX is an array framework for machine learning on Apple silicon, brought to you by Apple machine learning research.
  dev_url: https://ml-explore.github.io/mlx/build/html/index.html
  doc_url: https://github.com/ml-explore/mlx

extra:
  recipe-maintainers:
    - xhochy
    - ngam
