{% set name = "mlx" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # There are no sources on PyPI
  url: https://github.com/ml-explore/mlx/archive/v{{ version }}.tar.gz
  sha256: 87ce2b5809955635e2c111850ab30db3c1b3164ac4494df980c1b3bdc3347d8c
  patches:
    - 0001-Use-CMAKE_SYSTEM_PROCESSOR-instead-of-CMAKE_HOST_SYS.patch

build:
  skip: true  # [win]
  number: 1

requirements:
  build:
    # need python in the build section to properly build the extensions
    - python
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    # we need to use apple's compilers on arm
    # otherwise we cannot expose all of the needed metal capabilities
    # and we get "device not found" type of errors
    - {{ compiler('c') }}                 # [not (osx and arm64)]
    - {{ compiler('cxx') }}               # [not (osx and arm64)] 
    - cmake
    - ninja
  host:
    - python
    - pip
    - pybind11
    - blas     # [not (osx and arm64)]
    - libblas  # [not (osx and arm64)]
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]


test:
  source_files:
    - python/
  imports:
    - mlx
    # "core" gets built as an extension and it requires python in build
    # testing locally showed that the extension gets built with the wrong python otherwise
    - mlx.core
  requires:
    - pip
    # test dependencies
    - numpy
  commands:
    - pip check
    # Tests are passing only if you have more than 8GB of RAM.
    - python -m unittest discover python/tests  # [osx and arm64]

about:
  home: https://github.com/ml-explore/mlx
  summary: An array framework for Apple silicon
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
