{% set name = "mlx" %}
{% set version = "0.27.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # There are no sources on PyPI
  url: https://github.com/ml-explore/mlx/archive/v{{ version }}.tar.gz
  sha256: eec64e74c1566c06a9318d47ef3e20e2d54d74912bb737b9d0cc5546a1464372
  patches:
    - 0001-Omit-visionOS-from-sources.patch

build:
  skip: true  # [win or py<39 or (osx and x86_64)]
  number: 0

requirements:
  build:
    # need python in the build section to properly build the extensions
    - python
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.24
    - ninja
  host:
    - python
    - pip
    - nanobind 2.2.0
    - setuptools >=42
    - libblas     # [not (osx and arm64)]
    - libcblas    # [not (osx and arm64)]
    - liblapack   # [not (osx and arm64)]
    - liblapacke  # [not (osx and arm64)]
  run:
    - python

test:
  source_files:
    - python/
  imports:
    - mlx
    - mlx.core
  requires:
    - pip
    # test dependencies
    - numpy
  commands:
    - pip check
    # Tests are passing only if you have more than 8GB of RAM.
    - python -m unittest discover python/tests  # [osx and arm64]

about:
  home: https://github.com/ml-explore/mlx
  summary: An array framework for Apple silicon
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    MLX is an array framework for machine learning on Apple silicon, brought to you by Apple machine learning research.
  dev_url: https://ml-explore.github.io/mlx/build/html/index.html
  doc_url: https://github.com/ml-explore/mlx

extra:
  recipe-maintainers:
    - xhochy
    - ngam
