{% set name = "mlx" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # There are no sources on PyPI
  - url: https://github.com/ml-explore/mlx/archive/v{{ version }}.tar.gz
    sha256: 4c4d6fd2630895d30ad9e576499211736d1c549f63b319c796851bb828513a7f
  - url: https://github.com/wjakob/nanobind/archive/03ebcb883a8658706bada56e7bc11faf2e2b3f67.zip
    sha256: cdadb150a0534582bc1760cd1ae2e9b99b8b3cbc09a1ef462d9aebd1070764c4
    folder: nanobind
  - url: https://github.com/Tessil/robin-map/archive/68ff7325b3898fca267a103bad5c509e8861144d.tar.gz
    sha256: 98e79b94950cbf6c645205d07c4752daa4926ecff5a0cf914c134ba59b9b1c29
    folder: nanobind/ext/robin_map

build:
  skip: true  # [win or py<39 or (osx and x86_64)]
  number: 0

requirements:
  build:
    # need python in the build section to properly build the extensions
    - python
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    # - nanobind
    - blas       # [not (osx and arm64)]
    - libblas    # [not (osx and arm64)]
    - liblapack  # [not (osx and arm64)]
  run:
    - python

test:
  source_files:
    - python/
  imports:
    - mlx
    - mlx.core
  requires:
    - pip
    # test dependencies
    - numpy
  commands:
    - pip check
    # Tests are passing only if you have more than 8GB of RAM.
    - python -m unittest discover python/tests  # [osx and arm64]

about:
  home: https://github.com/ml-explore/mlx
  summary: An array framework for Apple silicon
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    MLX is an array framework for machine learning on Apple silicon, brought to you by Apple machine learning research.
  dev_url: https://ml-explore.github.io/mlx/build/html/index.html
  doc_url: https://github.com/ml-explore/mlx

extra:
  recipe-maintainers:
    - xhochy
    - ngam
