azure:
  settings_osx:
    pool:
      vmImage: macos-13
  store_build_artifacts: true
bot:
  automerge: true
  inspection: update-grayskull
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
conda_install_tool: pixi
conda_build_tool: rattler-build
github:
  branch_name: main
  tooling_branch_name: main
test: native
