azure:
  settings_osx:
    pool:
      # macos-13 is in beta ... but let's try it
      vmImage: macos-13
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
test: native
