# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

#                             VVVVVV  minimum `pixi` version
"$schema" = "https://pixi.sh/v0.36.0/schema/manifest/schema.json"

[project]
name = "mlx-feedstock"
version = "3.47.1"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/mlx-feedstock"
authors = ["@conda-forge/mlx"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
python = "3.12.*"

[tasks]
[tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in conda-build build directory."
[tasks.build]
cmd = "conda-build build recipe"
description = "Build mlx-feedstock directly (without setup scripts), no particular variant specified"
[tasks.debug]
cmd = "conda-build debug recipe"
description = "Debug mlx-feedstock directly (without setup scripts), no particular variant specified"
[tasks."build-linux_64_numpy2.0python3.10.____cpython"]
cmd = "conda-build build recipe -m .ci_support/linux_64_numpy2.0python3.10.____cpython.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_64_numpy2.0python3.10.____cpython.yaml"
description = "Build mlx-feedstock with variant linux_64_numpy2.0python3.10.____cpython directly (without setup scripts)"
[tasks."debug-linux_64_numpy2.0python3.10.____cpython"]
cmd = "conda-build debug recipe -m .ci_support/linux_64_numpy2.0python3.10.____cpython.yaml"
description = "Debug mlx-feedstock with variant linux_64_numpy2.0python3.10.____cpython directly (without setup scripts)"
[tasks."inspect-linux_64_numpy2.0python3.10.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy2.0python3.10.____cpython.yaml"
description = "List contents of mlx-feedstock packages built for variant linux_64_numpy2.0python3.10.____cpython"
[tasks."build-linux_64_numpy2.0python3.11.____cpython"]
cmd = "conda-build build recipe -m .ci_support/linux_64_numpy2.0python3.11.____cpython.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_64_numpy2.0python3.11.____cpython.yaml"
description = "Build mlx-feedstock with variant linux_64_numpy2.0python3.11.____cpython directly (without setup scripts)"
[tasks."debug-linux_64_numpy2.0python3.11.____cpython"]
cmd = "conda-build debug recipe -m .ci_support/linux_64_numpy2.0python3.11.____cpython.yaml"
description = "Debug mlx-feedstock with variant linux_64_numpy2.0python3.11.____cpython directly (without setup scripts)"
[tasks."inspect-linux_64_numpy2.0python3.11.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy2.0python3.11.____cpython.yaml"
description = "List contents of mlx-feedstock packages built for variant linux_64_numpy2.0python3.11.____cpython"
[tasks."build-linux_64_numpy2.0python3.12.____cpython"]
cmd = "conda-build build recipe -m .ci_support/linux_64_numpy2.0python3.12.____cpython.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_64_numpy2.0python3.12.____cpython.yaml"
description = "Build mlx-feedstock with variant linux_64_numpy2.0python3.12.____cpython directly (without setup scripts)"
[tasks."debug-linux_64_numpy2.0python3.12.____cpython"]
cmd = "conda-build debug recipe -m .ci_support/linux_64_numpy2.0python3.12.____cpython.yaml"
description = "Debug mlx-feedstock with variant linux_64_numpy2.0python3.12.____cpython directly (without setup scripts)"
[tasks."inspect-linux_64_numpy2.0python3.12.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy2.0python3.12.____cpython.yaml"
description = "List contents of mlx-feedstock packages built for variant linux_64_numpy2.0python3.12.____cpython"
[tasks."build-linux_64_numpy2.0python3.9.____cpython"]
cmd = "conda-build build recipe -m .ci_support/linux_64_numpy2.0python3.9.____cpython.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_64_numpy2.0python3.9.____cpython.yaml"
description = "Build mlx-feedstock with variant linux_64_numpy2.0python3.9.____cpython directly (without setup scripts)"
[tasks."debug-linux_64_numpy2.0python3.9.____cpython"]
cmd = "conda-build debug recipe -m .ci_support/linux_64_numpy2.0python3.9.____cpython.yaml"
description = "Debug mlx-feedstock with variant linux_64_numpy2.0python3.9.____cpython directly (without setup scripts)"
[tasks."inspect-linux_64_numpy2.0python3.9.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy2.0python3.9.____cpython.yaml"
description = "List contents of mlx-feedstock packages built for variant linux_64_numpy2.0python3.9.____cpython"
[tasks."build-linux_64_numpy2python3.13.____cp313"]
cmd = "conda-build build recipe -m .ci_support/linux_64_numpy2python3.13.____cp313.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_64_numpy2python3.13.____cp313.yaml"
description = "Build mlx-feedstock with variant linux_64_numpy2python3.13.____cp313 directly (without setup scripts)"
[tasks."debug-linux_64_numpy2python3.13.____cp313"]
cmd = "conda-build debug recipe -m .ci_support/linux_64_numpy2python3.13.____cp313.yaml"
description = "Debug mlx-feedstock with variant linux_64_numpy2python3.13.____cp313 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy2python3.13.____cp313"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy2python3.13.____cp313.yaml"
description = "List contents of mlx-feedstock packages built for variant linux_64_numpy2python3.13.____cp313"
[tasks."build-linux_aarch64_numpy2.0python3.10.____cpython"]
cmd = "conda-build build recipe -m .ci_support/linux_aarch64_numpy2.0python3.10.____cpython.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_aarch64_numpy2.0python3.10.____cpython.yaml"
description = "Build mlx-feedstock with variant linux_aarch64_numpy2.0python3.10.____cpython directly (without setup scripts)"
[tasks."debug-linux_aarch64_numpy2.0python3.10.____cpython"]
cmd = "conda-build debug recipe -m .ci_support/linux_aarch64_numpy2.0python3.10.____cpython.yaml"
description = "Debug mlx-feedstock with variant linux_aarch64_numpy2.0python3.10.____cpython directly (without setup scripts)"
[tasks."inspect-linux_aarch64_numpy2.0python3.10.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_numpy2.0python3.10.____cpython.yaml"
description = "List contents of mlx-feedstock packages built for variant linux_aarch64_numpy2.0python3.10.____cpython"
[tasks."build-linux_aarch64_numpy2.0python3.11.____cpython"]
cmd = "conda-build build recipe -m .ci_support/linux_aarch64_numpy2.0python3.11.____cpython.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_aarch64_numpy2.0python3.11.____cpython.yaml"
description = "Build mlx-feedstock with variant linux_aarch64_numpy2.0python3.11.____cpython directly (without setup scripts)"
[tasks."debug-linux_aarch64_numpy2.0python3.11.____cpython"]
cmd = "conda-build debug recipe -m .ci_support/linux_aarch64_numpy2.0python3.11.____cpython.yaml"
description = "Debug mlx-feedstock with variant linux_aarch64_numpy2.0python3.11.____cpython directly (without setup scripts)"
[tasks."inspect-linux_aarch64_numpy2.0python3.11.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_numpy2.0python3.11.____cpython.yaml"
description = "List contents of mlx-feedstock packages built for variant linux_aarch64_numpy2.0python3.11.____cpython"
[tasks."build-linux_aarch64_numpy2.0python3.12.____cpython"]
cmd = "conda-build build recipe -m .ci_support/linux_aarch64_numpy2.0python3.12.____cpython.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_aarch64_numpy2.0python3.12.____cpython.yaml"
description = "Build mlx-feedstock with variant linux_aarch64_numpy2.0python3.12.____cpython directly (without setup scripts)"
[tasks."debug-linux_aarch64_numpy2.0python3.12.____cpython"]
cmd = "conda-build debug recipe -m .ci_support/linux_aarch64_numpy2.0python3.12.____cpython.yaml"
description = "Debug mlx-feedstock with variant linux_aarch64_numpy2.0python3.12.____cpython directly (without setup scripts)"
[tasks."inspect-linux_aarch64_numpy2.0python3.12.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_numpy2.0python3.12.____cpython.yaml"
description = "List contents of mlx-feedstock packages built for variant linux_aarch64_numpy2.0python3.12.____cpython"
[tasks."build-linux_aarch64_numpy2.0python3.9.____cpython"]
cmd = "conda-build build recipe -m .ci_support/linux_aarch64_numpy2.0python3.9.____cpython.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_aarch64_numpy2.0python3.9.____cpython.yaml"
description = "Build mlx-feedstock with variant linux_aarch64_numpy2.0python3.9.____cpython directly (without setup scripts)"
[tasks."debug-linux_aarch64_numpy2.0python3.9.____cpython"]
cmd = "conda-build debug recipe -m .ci_support/linux_aarch64_numpy2.0python3.9.____cpython.yaml"
description = "Debug mlx-feedstock with variant linux_aarch64_numpy2.0python3.9.____cpython directly (without setup scripts)"
[tasks."inspect-linux_aarch64_numpy2.0python3.9.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_numpy2.0python3.9.____cpython.yaml"
description = "List contents of mlx-feedstock packages built for variant linux_aarch64_numpy2.0python3.9.____cpython"
[tasks."build-linux_aarch64_numpy2python3.13.____cp313"]
cmd = "conda-build build recipe -m .ci_support/linux_aarch64_numpy2python3.13.____cp313.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_aarch64_numpy2python3.13.____cp313.yaml"
description = "Build mlx-feedstock with variant linux_aarch64_numpy2python3.13.____cp313 directly (without setup scripts)"
[tasks."debug-linux_aarch64_numpy2python3.13.____cp313"]
cmd = "conda-build debug recipe -m .ci_support/linux_aarch64_numpy2python3.13.____cp313.yaml"
description = "Debug mlx-feedstock with variant linux_aarch64_numpy2python3.13.____cp313 directly (without setup scripts)"
[tasks."inspect-linux_aarch64_numpy2python3.13.____cp313"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_numpy2python3.13.____cp313.yaml"
description = "List contents of mlx-feedstock packages built for variant linux_aarch64_numpy2python3.13.____cp313"
[tasks."build-osx_arm64_numpy2.0python3.10.____cpython"]
cmd = "conda-build build recipe -m .ci_support/osx_arm64_numpy2.0python3.10.____cpython.yaml --suppress-variables --clobber-file .ci_support/clobber_osx_arm64_numpy2.0python3.10.____cpython.yaml"
description = "Build mlx-feedstock with variant osx_arm64_numpy2.0python3.10.____cpython directly (without setup scripts)"
[tasks."debug-osx_arm64_numpy2.0python3.10.____cpython"]
cmd = "conda-build debug recipe -m .ci_support/osx_arm64_numpy2.0python3.10.____cpython.yaml"
description = "Debug mlx-feedstock with variant osx_arm64_numpy2.0python3.10.____cpython directly (without setup scripts)"
[tasks."inspect-osx_arm64_numpy2.0python3.10.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_numpy2.0python3.10.____cpython.yaml"
description = "List contents of mlx-feedstock packages built for variant osx_arm64_numpy2.0python3.10.____cpython"
[tasks."build-osx_arm64_numpy2.0python3.11.____cpython"]
cmd = "conda-build build recipe -m .ci_support/osx_arm64_numpy2.0python3.11.____cpython.yaml --suppress-variables --clobber-file .ci_support/clobber_osx_arm64_numpy2.0python3.11.____cpython.yaml"
description = "Build mlx-feedstock with variant osx_arm64_numpy2.0python3.11.____cpython directly (without setup scripts)"
[tasks."debug-osx_arm64_numpy2.0python3.11.____cpython"]
cmd = "conda-build debug recipe -m .ci_support/osx_arm64_numpy2.0python3.11.____cpython.yaml"
description = "Debug mlx-feedstock with variant osx_arm64_numpy2.0python3.11.____cpython directly (without setup scripts)"
[tasks."inspect-osx_arm64_numpy2.0python3.11.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_numpy2.0python3.11.____cpython.yaml"
description = "List contents of mlx-feedstock packages built for variant osx_arm64_numpy2.0python3.11.____cpython"
[tasks."build-osx_arm64_numpy2.0python3.12.____cpython"]
cmd = "conda-build build recipe -m .ci_support/osx_arm64_numpy2.0python3.12.____cpython.yaml --suppress-variables --clobber-file .ci_support/clobber_osx_arm64_numpy2.0python3.12.____cpython.yaml"
description = "Build mlx-feedstock with variant osx_arm64_numpy2.0python3.12.____cpython directly (without setup scripts)"
[tasks."debug-osx_arm64_numpy2.0python3.12.____cpython"]
cmd = "conda-build debug recipe -m .ci_support/osx_arm64_numpy2.0python3.12.____cpython.yaml"
description = "Debug mlx-feedstock with variant osx_arm64_numpy2.0python3.12.____cpython directly (without setup scripts)"
[tasks."inspect-osx_arm64_numpy2.0python3.12.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_numpy2.0python3.12.____cpython.yaml"
description = "List contents of mlx-feedstock packages built for variant osx_arm64_numpy2.0python3.12.____cpython"
[tasks."build-osx_arm64_numpy2.0python3.9.____cpython"]
cmd = "conda-build build recipe -m .ci_support/osx_arm64_numpy2.0python3.9.____cpython.yaml --suppress-variables --clobber-file .ci_support/clobber_osx_arm64_numpy2.0python3.9.____cpython.yaml"
description = "Build mlx-feedstock with variant osx_arm64_numpy2.0python3.9.____cpython directly (without setup scripts)"
[tasks."debug-osx_arm64_numpy2.0python3.9.____cpython"]
cmd = "conda-build debug recipe -m .ci_support/osx_arm64_numpy2.0python3.9.____cpython.yaml"
description = "Debug mlx-feedstock with variant osx_arm64_numpy2.0python3.9.____cpython directly (without setup scripts)"
[tasks."inspect-osx_arm64_numpy2.0python3.9.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_numpy2.0python3.9.____cpython.yaml"
description = "List contents of mlx-feedstock packages built for variant osx_arm64_numpy2.0python3.9.____cpython"
[tasks."build-osx_arm64_numpy2python3.13.____cp313"]
cmd = "conda-build build recipe -m .ci_support/osx_arm64_numpy2python3.13.____cp313.yaml --suppress-variables --clobber-file .ci_support/clobber_osx_arm64_numpy2python3.13.____cp313.yaml"
description = "Build mlx-feedstock with variant osx_arm64_numpy2python3.13.____cp313 directly (without setup scripts)"
[tasks."debug-osx_arm64_numpy2python3.13.____cp313"]
cmd = "conda-build debug recipe -m .ci_support/osx_arm64_numpy2python3.13.____cp313.yaml"
description = "Debug mlx-feedstock with variant osx_arm64_numpy2python3.13.____cp313 directly (without setup scripts)"
[tasks."inspect-osx_arm64_numpy2python3.13.____cp313"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_numpy2python3.13.____cp313.yaml"
description = "List contents of mlx-feedstock packages built for variant osx_arm64_numpy2python3.13.____cp313"

[feature.smithy.dependencies]
conda-smithy = "*"
[feature.smithy.tasks.build-locally]
cmd = "python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[feature.smithy.tasks.smithy]
cmd = "conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[feature.smithy.tasks.rerender]
cmd = "conda-smithy rerender"
description = "Rerender the feedstock."
[feature.smithy.tasks.lint]
cmd = "conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[environments]
smithy = ["smithy"]
# This is a copy of default, to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = []
